//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salamandra.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewsTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewsTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Salamandra.Strings.ViewsTexts", typeof(ViewsTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected events?.
        /// </summary>
        public static string EventListWindow_AreYouSureDelete {
            get {
                return ResourceManager.GetString("EventListWindow_AreYouSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all events?.
        /// </summary>
        public static string EventListWindow_AreYouSureDeleteAll {
            get {
                return ResourceManager.GetString("EventListWindow_AreYouSureDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the expired events?.
        /// </summary>
        public static string EventListWindow_AreYouSureDeleteExpired {
            get {
                return ResourceManager.GetString("EventListWindow_AreYouSureDeleteExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string EventListWindow_Delete {
            get {
                return ResourceManager.GetString("EventListWindow_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all events.
        /// </summary>
        public static string EventListWindow_DeleteAll {
            get {
                return ResourceManager.GetString("EventListWindow_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete expired.
        /// </summary>
        public static string EventListWindow_DeleteExpired {
            get {
                return ResourceManager.GetString("EventListWindow_DeleteExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EventListWindow_Edit {
            get {
                return ResourceManager.GetString("EventListWindow_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error opening the event list file.
        /// </summary>
        public static string EventListWindow_ErrorOpeningList {
            get {
                return ResourceManager.GetString("EventListWindow_ErrorOpeningList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error saving the event list file.
        /// </summary>
        public static string EventListWindow_ErrorSavingList {
            get {
                return ResourceManager.GetString("EventListWindow_ErrorSavingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration.
        /// </summary>
        public static string EventListWindow_Expiration {
            get {
                return ResourceManager.GetString("EventListWindow_Expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string EventListWindow_File {
            get {
                return ResourceManager.GetString("EventListWindow_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string EventListWindow_Hours {
            get {
                return ResourceManager.GetString("EventListWindow_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string EventListWindow_Mode {
            get {
                return ResourceManager.GetString("EventListWindow_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string EventListWindow_New {
            get {
                return ResourceManager.GetString("EventListWindow_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string EventListWindow_Open {
            get {
                return ResourceManager.GetString("EventListWindow_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save....
        /// </summary>
        public static string EventListWindow_Save {
            get {
                return ResourceManager.GetString("EventListWindow_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string EventListWindow_Time {
            get {
                return ResourceManager.GetString("EventListWindow_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week Days.
        /// </summary>
        public static string EventListWindow_WeekDays {
            get {
                return ResourceManager.GetString("EventListWindow_WeekDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string EventListWindow_WindowTitle {
            get {
                return ResourceManager.GetString("EventListWindow_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cue.
        /// </summary>
        public static string EventWindow_Cue {
            get {
                return ResourceManager.GetString("EventWindow_Cue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and Time.
        /// </summary>
        public static string EventWindow_DateAndTime {
            get {
                return ResourceManager.GetString("EventWindow_DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable maximum wait.
        /// </summary>
        public static string EventWindow_EnableMaximumWait {
            get {
                return ResourceManager.GetString("EventWindow_EnableMaximumWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Type.
        /// </summary>
        public static string EventWindow_EventType {
            get {
                return ResourceManager.GetString("EventWindow_EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date and time.
        /// </summary>
        public static string EventWindow_ExpirationDateTime {
            get {
                return ResourceManager.GetString("EventWindow_ExpirationDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Priority.
        /// </summary>
        public static string EventWindow_HighPriority {
            get {
                return ResourceManager.GetString("EventWindow_HighPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediate.
        /// </summary>
        public static string EventWindow_Immediate {
            get {
                return ResourceManager.GetString("EventWindow_Immediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Priority.
        /// </summary>
        public static string EventWindow_LowPriority {
            get {
                return ResourceManager.GetString("EventWindow_LowPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Wait.
        /// </summary>
        public static string EventWindow_MaximumWait {
            get {
                return ResourceManager.GetString("EventWindow_MaximumWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action after waiting time.
        /// </summary>
        public static string EventWindow_MaximumWaitAction {
            get {
                return ResourceManager.GetString("EventWindow_MaximumWaitAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum wait time.
        /// </summary>
        public static string EventWindow_MaximumWaitTime {
            get {
                return ResourceManager.GetString("EventWindow_MaximumWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order and Priority.
        /// </summary>
        public static string EventWindow_OrderAndPriority {
            get {
                return ResourceManager.GetString("EventWindow_OrderAndPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other hours.
        /// </summary>
        public static string EventWindow_OtherHours {
            get {
                return ResourceManager.GetString("EventWindow_OtherHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue order.
        /// </summary>
        public static string EventWindow_QueueOrder {
            get {
                return ResourceManager.GetString("EventWindow_QueueOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting date and time.
        /// </summary>
        public static string EventWindow_StartingDateTime {
            get {
                return ResourceManager.GetString("EventWindow_StartingDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time and days.
        /// </summary>
        public static string EventWindow_TimeAndDay {
            get {
                return ResourceManager.GetString("EventWindow_TimeAndDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A delayed start playback event may not have the desired effect..
        /// </summary>
        public static string EventWindow_Validation_DelayedStartPlayback {
            get {
                return ResourceManager.GetString("EventWindow_Validation_DelayedStartPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expiration date must be later than the start date..
        /// </summary>
        public static string EventWindow_Validation_ExpirationAfterStarting {
            get {
                return ResourceManager.GetString("EventWindow_Validation_ExpirationAfterStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The days that the event will play must be selected..
        /// </summary>
        public static string EventWindow_Validation_MustSelectDays {
            get {
                return ResourceManager.GetString("EventWindow_Validation_MustSelectDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file must be selected..
        /// </summary>
        public static string EventWindow_Validation_MustSelectFile {
            get {
                return ResourceManager.GetString("EventWindow_Validation_MustSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hours that the event will play must be selected..
        /// </summary>
        public static string EventWindow_Validation_MustSelectHours {
            get {
                return ResourceManager.GetString("EventWindow_Validation_MustSelectHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum wait time must be greater than zero..
        /// </summary>
        public static string EventWindow_Validation_WaitingTimeGreaterThanZero {
            get {
                return ResourceManager.GetString("EventWindow_Validation_WaitingTimeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week Days.
        /// </summary>
        public static string EventWindow_WeekDays {
            get {
                return ResourceManager.GetString("EventWindow_WeekDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string EventWindow_WindowTitle {
            get {
                return ResourceManager.GetString("EventWindow_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string FileFormats_All {
            get {
                return ResourceManager.GetString("FileFormats_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio files.
        /// </summary>
        public static string FileFormats_Audio {
            get {
                return ResourceManager.GetString("FileFormats_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string FileFormats_Playlist {
            get {
                return ResourceManager.GetString("FileFormats_Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled events file.
        /// </summary>
        public static string FileFormats_ScheduleEvents {
            get {
                return ResourceManager.GetString("FileFormats_ScheduleEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add audio files....
        /// </summary>
        public static string MainWindow_AddAudioTracks {
            get {
                return ResourceManager.GetString("MainWindow_AddAudioTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding files to the playlist....
        /// </summary>
        public static string MainWindow_AddingFilesToPlaylist {
            get {
                return ResourceManager.GetString("MainWindow_AddingFilesToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add playlist file....
        /// </summary>
        public static string MainWindow_AddPlaylistTrack {
            get {
                return ResourceManager.GetString("MainWindow_AddPlaylistTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add random track....
        /// </summary>
        public static string MainWindow_AddRandomTrack {
            get {
                return ResourceManager.GetString("MainWindow_AddRandomTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add command to stop playlist....
        /// </summary>
        public static string MainWindow_AddStopPlaylistTrack {
            get {
                return ResourceManager.GetString("MainWindow_AddStopPlaylistTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add time announcement track....
        /// </summary>
        public static string MainWindow_AddTimeAnnouncement {
            get {
                return ResourceManager.GetString("MainWindow_AddTimeAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cue.
        /// </summary>
        public static string MainWindow_Cue {
            get {
                return ResourceManager.GetString("MainWindow_Cue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected tracks.
        /// </summary>
        public static string MainWindow_Delete {
            get {
                return ResourceManager.GetString("MainWindow_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all tracks.
        /// </summary>
        public static string MainWindow_DeleteAll {
            get {
                return ResourceManager.GetString("MainWindow_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MainWindow_Edit {
            get {
                return ResourceManager.GetString("MainWindow_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error opening the log folder..
        /// </summary>
        public static string MainWindow_Error_OpeningLogFolder {
            get {
                return ResourceManager.GetString("MainWindow_Error_OpeningLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error opening today&apos;s log..
        /// </summary>
        public static string MainWindow_Error_OpeningTodayLog {
            get {
                return ResourceManager.GetString("MainWindow_Error_OpeningTodayLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error acessing the playlist file..
        /// </summary>
        public static string MainWindow_Error_PlaylistFile {
            get {
                return ResourceManager.GetString("MainWindow_Error_PlaylistFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while opening the playlist..
        /// </summary>
        public static string MainWindow_Error_PlaylistOpenGeneric {
            get {
                return ResourceManager.GetString("MainWindow_Error_PlaylistOpenGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error when parsing the playlist file..
        /// </summary>
        public static string MainWindow_Error_PlaylistParsing {
            get {
                return ResourceManager.GetString("MainWindow_Error_PlaylistParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error saving the playlist..
        /// </summary>
        public static string MainWindow_Error_PlaylistSaveGeneric {
            get {
                return ResourceManager.GetString("MainWindow_Error_PlaylistSaveGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error saving the scheduled events..
        /// </summary>
        public static string MainWindow_Error_ScheduleSaveGeneric {
            get {
                return ResourceManager.GetString("MainWindow_Error_ScheduleSaveGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error in the audio device that forced playback to stop..
        /// </summary>
        public static string MainWindow_Error_SoundDevice {
            get {
                return ResourceManager.GetString("MainWindow_Error_SoundDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The log file doesn&apos;t exist yet. Check to see if there has been any player activity or if logging is active..
        /// </summary>
        public static string MainWindow_Error_TodayLogDoesntExist {
            get {
                return ResourceManager.GetString("MainWindow_Error_TodayLogDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unhandled error on playlist..
        /// </summary>
        public static string MainWindow_Error_UnhandledPlaylistError {
            get {
                return ResourceManager.GetString("MainWindow_Error_UnhandledPlaylistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MainWindow_File {
            get {
                return ResourceManager.GetString("MainWindow_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading playlist....
        /// </summary>
        public static string MainWindow_LoadingPlaylist {
            get {
                return ResourceManager.GetString("MainWindow_LoadingPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as next track.
        /// </summary>
        public static string MainWindow_MarkAsNext {
            get {
                return ResourceManager.GetString("MainWindow_MarkAsNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string MainWindow_Media {
            get {
                return ResourceManager.GetString("MainWindow_Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string MainWindow_New {
            get {
                return ResourceManager.GetString("MainWindow_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now Playing.
        /// </summary>
        public static string MainWindow_NowPlaying {
            get {
                return ResourceManager.GetString("MainWindow_NowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string MainWindow_NowPlaying_EndTime {
            get {
                return ResourceManager.GetString("MainWindow_NowPlaying_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Time.
        /// </summary>
        public static string MainWindow_NowPlaying_RemainingTime {
            get {
                return ResourceManager.GetString("MainWindow_NowPlaying_RemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string MainWindow_Open {
            get {
                return ResourceManager.GetString("MainWindow_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open logs folder.
        /// </summary>
        public static string MainWindow_OpenLogFolder {
            get {
                return ResourceManager.GetString("MainWindow_OpenLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open today&apos;s log.
        /// </summary>
        public static string MainWindow_OpenTodayLog {
            get {
                return ResourceManager.GetString("MainWindow_OpenTodayLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Track.
        /// </summary>
        public static string MainWindow_PlayingNext {
            get {
                return ResourceManager.GetString("MainWindow_PlayingNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string MainWindow_Playlist {
            get {
                return ResourceManager.GetString("MainWindow_Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string MainWindow_Playlist_Duration {
            get {
                return ResourceManager.GetString("MainWindow_Playlist_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MainWindow_Playlist_File {
            get {
                return ResourceManager.GetString("MainWindow_Playlist_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player is still running. Are you sure that you want to close?.
        /// </summary>
        public static string MainWindow_PlaylistStillPlaying {
            get {
                return ResourceManager.GetString("MainWindow_PlaylistStillPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes to the playlist. Do you want to save them?.
        /// </summary>
        public static string MainWindow_PlaylistUnsavedChanges {
            get {
                return ResourceManager.GetString("MainWindow_PlaylistUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play next track.
        /// </summary>
        public static string MainWindow_PlayNextTrack {
            get {
                return ResourceManager.GetString("MainWindow_PlayNextTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play selected track.
        /// </summary>
        public static string MainWindow_PlaySelectedTrack {
            get {
                return ResourceManager.GetString("MainWindow_PlaySelectedTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MainWindow_Save {
            get {
                return ResourceManager.GetString("MainWindow_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        public static string MainWindow_SaveAs {
            get {
                return ResourceManager.GetString("MainWindow_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainWindow_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle playlist.
        /// </summary>
        public static string MainWindow_ShufflePlaylist {
            get {
                return ResourceManager.GetString("MainWindow_ShufflePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start playback.
        /// </summary>
        public static string MainWindow_StartPlayback {
            get {
                return ResourceManager.GetString("MainWindow_StartPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop after current track.
        /// </summary>
        public static string MainWindow_StopAfterCurrentTrack {
            get {
                return ResourceManager.GetString("MainWindow_StopAfterCurrentTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop playback.
        /// </summary>
        public static string MainWindow_StopPlayback {
            get {
                return ResourceManager.GetString("MainWindow_StopPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string MainWindow_Tags_Album {
            get {
                return ResourceManager.GetString("MainWindow_Tags_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string MainWindow_Tags_Artist {
            get {
                return ResourceManager.GetString("MainWindow_Tags_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string MainWindow_Tags_Comment {
            get {
                return ResourceManager.GetString("MainWindow_Tags_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string MainWindow_Tags_Genre {
            get {
                return ResourceManager.GetString("MainWindow_Tags_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string MainWindow_Tags_Title {
            get {
                return ResourceManager.GetString("MainWindow_Tags_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string MainWindow_Tags_Year {
            get {
                return ResourceManager.GetString("MainWindow_Tags_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string MainWindow_Tools {
            get {
                return ResourceManager.GetString("MainWindow_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add audio files....
        /// </summary>
        public static string MainWindow_Tooltip_AddAudioFiles {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_AddAudioFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete track after playing.
        /// </summary>
        public static string MainWindow_Tooltip_DeleteMode {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_DeleteMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected tracks....
        /// </summary>
        public static string MainWindow_Tooltip_DeleteSelectedFiles {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_DeleteSelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard late events.
        /// </summary>
        public static string MainWindow_Tooltip_DiscardLateEvents {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_DiscardLateEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/disable events.
        /// </summary>
        public static string MainWindow_Tooltip_EnableDisableEvents {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_EnableDisableEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop track.
        /// </summary>
        public static string MainWindow_Tooltip_LoopMode {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_LoopMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute/unmute volume.
        /// </summary>
        public static string MainWindow_Tooltip_MuteUnmuteVolume {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_MuteUnmuteVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New playlist.
        /// </summary>
        public static string MainWindow_Tooltip_NewPlaylist {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_NewPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play next track.
        /// </summary>
        public static string MainWindow_Tooltip_NextTrack {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_NextTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open scheduled events list.
        /// </summary>
        public static string MainWindow_Tooltip_OpenEventList {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_OpenEventList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open playlist.
        /// </summary>
        public static string MainWindow_Tooltip_OpenPlaylist {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_OpenPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause current track.
        /// </summary>
        public static string MainWindow_Tooltip_Pause {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play events.
        /// </summary>
        public static string MainWindow_Tooltip_PlayLateEvents {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_PlayLateEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist next track mode.
        /// </summary>
        public static string MainWindow_Tooltip_PlaylistMode {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_PlaylistMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save playlist.
        /// </summary>
        public static string MainWindow_Tooltip_SavePlaylist {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_SavePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainWindow_Tooltip_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start playback.
        /// </summary>
        public static string MainWindow_Tooltip_StartPlayback {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_StartPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop after current track.
        /// </summary>
        public static string MainWindow_Tooltip_StopAfterCurrentTrack {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_StopAfterCurrentTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop playback.
        /// </summary>
        public static string MainWindow_Tooltip_StopPlayback {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_StopPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Events.
        /// </summary>
        public static string MainWindow_UpcomingEvents {
            get {
                return ResourceManager.GetString("MainWindow_UpcomingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string MainWindow_UpcomingEvents_Mode {
            get {
                return ResourceManager.GetString("MainWindow_UpcomingEvents_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string MainWindow_UpcomingEvents_Name {
            get {
                return ResourceManager.GetString("MainWindow_UpcomingEvents_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string MainWindow_UpcomingEvents_Time {
            get {
                return ResourceManager.GetString("MainWindow_UpcomingEvents_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salamandra.
        /// </summary>
        public static string Misc_ApplicationTitle {
            get {
                return ResourceManager.GetString("Misc_ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Misc_Cancel {
            get {
                return ResourceManager.GetString("Misc_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Misc_Copy {
            get {
                return ResourceManager.GetString("Misc_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Misc_Cut {
            get {
                return ResourceManager.GetString("Misc_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediate.
        /// </summary>
        public static string Misc_Events_Immediate {
            get {
                return ResourceManager.GetString("Misc_Events_Immediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delayed.
        /// </summary>
        public static string Misc_Events_NotImmediate {
            get {
                return ResourceManager.GetString("Misc_Events_NotImmediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Misc_Ok {
            get {
                return ResourceManager.GetString("Misc_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Misc_Paste {
            get {
                return ResourceManager.GetString("Misc_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string Misc_SelectAll {
            get {
                return ResourceManager.GetString("Misc_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Announcement.
        /// </summary>
        public static string Misc_Track_TimeAnnouncement {
            get {
                return ResourceManager.GetString("Misc_Track_TimeAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to play the audio file..
        /// </summary>
        public static string PreListenWindow_Error_PlaybackError {
            get {
                return ResourceManager.GetString("PreListenWindow_Error_PlaybackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cue.
        /// </summary>
        public static string PreListenWindow_WindowTitle {
            get {
                return ResourceManager.GetString("PreListenWindow_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask when close while player is still active.
        /// </summary>
        public static string SettingsWindow_AskWhenCloseWhilePlaying {
            get {
                return ResourceManager.GetString("SettingsWindow_AskWhenCloseWhilePlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cue Sound Output Device.
        /// </summary>
        public static string SettingsWindow_CueOutputDevice {
            get {
                return ResourceManager.GetString("SettingsWindow_CueOutputDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Logs.
        /// </summary>
        public static string SettingsWindow_EnableLogs {
            get {
                return ResourceManager.GetString("SettingsWindow_EnableLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SettingsWindow_General {
            get {
                return ResourceManager.GetString("SettingsWindow_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep last state of &apos;Delete Mode&apos; on startup.
        /// </summary>
        public static string SettingsWindow_KeepDeleteModeLastState {
            get {
                return ResourceManager.GetString("SettingsWindow_KeepDeleteModeLastState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always keep events enabled on startup.
        /// </summary>
        public static string SettingsWindow_KeepEventsEnabledOnStartup {
            get {
                return ResourceManager.GetString("SettingsWindow_KeepEventsEnabledOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsWindow_Language {
            get {
                return ResourceManager.GetString("SettingsWindow_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs folder.
        /// </summary>
        public static string SettingsWindow_LogOutputPath {
            get {
                return ResourceManager.GetString("SettingsWindow_LogOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string SettingsWindow_Logs {
            get {
                return ResourceManager.GetString("SettingsWindow_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs are text files that report on playback activity on a daily basis, as well as errors like invalid files or output devices..
        /// </summary>
        public static string SettingsWindow_LogsExplanation {
            get {
                return ResourceManager.GetString("SettingsWindow_LogsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Sound Output Device.
        /// </summary>
        public static string SettingsWindow_MainOutputDevice {
            get {
                return ResourceManager.GetString("SettingsWindow_MainOutputDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open last playlist at startup.
        /// </summary>
        public static string SettingsWindow_OpenLastPlaylistOnStartup {
            get {
                return ResourceManager.GetString("SettingsWindow_OpenLastPlaylistOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs.
        /// </summary>
        public static string SettingsWindow_Outputs {
            get {
                return ResourceManager.GetString("SettingsWindow_Outputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle playlist at startup.
        /// </summary>
        public static string SettingsWindow_ShufflePlaylistOnStartup {
            get {
                return ResourceManager.GetString("SettingsWindow_ShufflePlaylistOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start playback at startup.
        /// </summary>
        public static string SettingsWindow_StartPlaybackOnStartup {
            get {
                return ResourceManager.GetString("SettingsWindow_StartPlaybackOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Announcement files path.
        /// </summary>
        public static string SettingsWindow_TimeAnnouncementFilesPath {
            get {
                return ResourceManager.GetString("SettingsWindow_TimeAnnouncementFilesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is necessary to choose a valid directory to generate the logs..
        /// </summary>
        public static string SettingsWindow_Validation_ValidLogFolder {
            get {
                return ResourceManager.GetString("SettingsWindow_Validation_ValidLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindow_WindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindow_WindowTitle", resourceCulture);
            }
        }
    }
}
