//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salamandra.Engine.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Salamandra.Engine.Strings.EnumResources", typeof(EnumResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string PlaylistMode_Default {
            get {
                return ResourceManager.GetString("PlaylistMode_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string PlaylistMode_Manual {
            get {
                return ResourceManager.GetString("PlaylistMode_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string PlaylistMode_Random {
            get {
                return ResourceManager.GetString("PlaylistMode_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string PlaylistMode_Repeat {
            get {
                return ResourceManager.GetString("PlaylistMode_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        public static string PlaylistMode_Shuffle {
            get {
                return ResourceManager.GetString("PlaylistMode_Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Track.
        /// </summary>
        public static string TrackScheduleType_AudioFileTrack {
            get {
                return ResourceManager.GetString("TrackScheduleType_AudioFileTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist File.
        /// </summary>
        public static string TrackScheduleType_OpenPlaylistTrack {
            get {
                return ResourceManager.GetString("TrackScheduleType_OpenPlaylistTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Schedule List.
        /// </summary>
        public static string TrackScheduleType_OpenScheduleTrack {
            get {
                return ResourceManager.GetString("TrackScheduleType_OpenScheduleTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random File Track.
        /// </summary>
        public static string TrackScheduleType_RandomFileTrack {
            get {
                return ResourceManager.GetString("TrackScheduleType_RandomFileTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Playback.
        /// </summary>
        public static string TrackScheduleType_StartPlaylistTrack {
            get {
                return ResourceManager.GetString("TrackScheduleType_StartPlaylistTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Playback.
        /// </summary>
        public static string TrackScheduleType_StopPlaylistTrack {
            get {
                return ResourceManager.GetString("TrackScheduleType_StopPlaylistTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run System Process/File.
        /// </summary>
        public static string TrackScheduleType_SystemProcessTrack {
            get {
                return ResourceManager.GetString("TrackScheduleType_SystemProcessTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Announcement.
        /// </summary>
        public static string TrackScheduleType_TimeAnnouncementTrack {
            get {
                return ResourceManager.GetString("TrackScheduleType_TimeAnnouncementTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string ViewLanguage_English {
            get {
                return ResourceManager.GetString("ViewLanguage_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string ViewLanguage_Portuguese {
            get {
                return ResourceManager.GetString("ViewLanguage_Portuguese", resourceCulture);
            }
        }
    }
}
